# Generated by Django 3.2.5 on 2021-07-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PembelajaranAbsensiGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_jam_belajar', models.CharField(max_length=50)),
                ('username_guru', models.CharField(max_length=150)),
                ('waktu_absen', models.DateTimeField()),
                ('terlambat', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tbl_pembelajaran_absensi_guru',
            },
        ),
        migrations.CreateModel(
            name='PembelajaranAbsensiSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_jam_belajar', models.CharField(max_length=50)),
                ('username_siswa', models.CharField(max_length=150)),
                ('waktu_absen', models.DateTimeField()),
                ('terlambat', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tbl_pembelajaran_absensi_siswa',
            },
        ),
        migrations.CreateModel(
            name='PembelajaranJadwalMataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_jadwal_pelajaran', models.CharField(max_length=20)),
                ('kd_mapel', models.CharField(max_length=20)),
                ('kd_rombel', models.CharField(max_length=30)),
                ('kd_guru', models.CharField(max_length=150)),
                ('hari', models.CharField(max_length=1)),
                ('mulai', models.DateTimeField()),
                ('selesai', models.DateTimeField()),
                ('urutan', models.IntegerField()),
                ('aktif', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tbl_pembelajaran_jadwal_mata_pelajaran',
            },
        ),
        migrations.CreateModel(
            name='PembelajaranJamBelajar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_jam_belajar', models.CharField(max_length=50)),
                ('kd_jadwal_pelajaran', models.CharField(max_length=20)),
                ('kd_ruangan', models.CharField(max_length=20)),
                ('token_absensi', models.CharField(max_length=8)),
                ('dimulai', models.DateTimeField()),
                ('selesai', models.DateTimeField()),
                ('total_hadir', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_pembelajaran_jam_belajar',
            },
        ),
        migrations.CreateModel(
            name='PembelajaranRuangAbsensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_jam_belajar', models.CharField(max_length=50)),
                ('username_guru', models.CharField(max_length=150)),
                ('username_siswa', models.CharField(max_length=150)),
                ('hadir', models.IntegerField()),
                ('izin', models.IntegerField()),
                ('tanpa_keterangan', models.IntegerField()),
                ('sakit', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_pembelajaran_ruang_absensi',
            },
        ),
    ]
