# Generated by Django 3.2.5 on 2021-07-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataMasterEkstrakurikuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_ekskul', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('deksripsi', models.TextField()),
                ('aktif', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tbl_data_master_ekstrakurikuler',
            },
        ),
        migrations.CreateModel(
            name='DataMasterInventori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_barang', models.CharField(max_length=25)),
                ('nama_barang', models.CharField(max_length=200)),
                ('deksripsi', models.TextField()),
                ('kd_ruangan', models.CharField(max_length=20)),
                ('kondisi', models.CharField(max_length=20)),
                ('qt', models.CharField(max_length=5)),
                ('kategori', models.CharField(max_length=50)),
                ('aktif', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tbl_data_master_inventori',
            },
        ),
        migrations.CreateModel(
            name='DataMasterJurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_jurusan', models.CharField(max_length=20)),
                ('nama_jurusan', models.CharField(max_length=100)),
                ('deksripsi', models.TextField()),
                ('aktif', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tbl_data_master_jurusan',
            },
        ),
        migrations.CreateModel(
            name='DataMasterMataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_mapel', models.CharField(max_length=20)),
                ('nama_mapel', models.CharField(max_length=200)),
                ('deksripsi', models.TextField()),
                ('tipe', models.CharField(max_length=30)),
                ('aktif', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tbl_data_master_mata_pelajaran',
            },
        ),
        migrations.CreateModel(
            name='DataMasterMataSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_data', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=100)),
                ('deksripsi', models.TextField()),
                ('nilai', models.TextField()),
            ],
            options={
                'db_table': 'tbl_data_master_sekolah',
            },
        ),
        migrations.CreateModel(
            name='DataMasterRombel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_rombel', models.CharField(max_length=30)),
                ('nama_rombel', models.CharField(max_length=100)),
                ('deksripsi', models.TextField()),
                ('kd_jurusan', models.CharField(max_length=20)),
                ('kd_semester', models.CharField(max_length=20)),
                ('jam_belajar', models.CharField(max_length=20)),
                ('aktif', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tbl_data_master_rombel',
            },
        ),
        migrations.CreateModel(
            name='DataMasterRuangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_ruangan', models.CharField(max_length=20)),
                ('nama_ruangan', models.CharField(max_length=200)),
                ('tipe', models.CharField(max_length=30)),
                ('kapasitas', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=30)),
                ('fasilitas', models.TextField()),
                ('aktif', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tbl_data_master_ruangan',
            },
        ),
        migrations.CreateModel(
            name='DataMasterSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_semester', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=100)),
                ('kd_tahun_ajaran', models.CharField(max_length=10)),
                ('mulai_tanggal', models.DateField()),
                ('akhir_tanggal', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('aktif', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tbl_data_master_semester',
            },
        ),
        migrations.CreateModel(
            name='DataMasterTahunAjaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_tahun_ajaran', models.CharField(max_length=10)),
                ('nama_tahun_ajaran', models.CharField(max_length=150)),
                ('mulai_tanggal', models.DateField()),
                ('akhir_tanggal', models.DateField()),
                ('status', models.DateField()),
                ('aktif', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tbl_data_master_tahun_ajaran',
            },
        ),
    ]
