from django.db import models
from datetime import date

# model siswa.
class SiswaData(models.Model):
    username = models.CharField(max_length=150, default="NULL")
    nis = models.CharField(max_length=30, default="NULL")
    nisn = models.CharField(max_length=30, default="NULL")
    nik = models.CharField(max_length=30, default="NULL")
    nama_lengkap = models.CharField(max_length=200, default="NULL")
    jenis_kelamin = models.CharField(max_length=5, default="NULL")
    tanggal_lahir = models.DateField(default=date.today)
    tempat_lahir = models.TextField()
    prov_lahir = models.CharField(max_length=15, default="NULL")
    kab_lahir = models.CharField(max_length=15, default="NULL")
    kec_lahir = models.CharField(max_length=15, default="NULL")
    desa_lahir = models.CharField(max_length=15, default="NULL")
    prov = models.CharField(max_length=15, default="NULL")
    kab = models.CharField(max_length=15, default="NULL")
    kec = models.CharField(max_length=15, default="NULL")
    desa = models.CharField(max_length=15, default="NULL")
    alamat = models.TextField()
    agama = models.CharField(max_length=5, default="NULL")
    golongan_darah = models.CharField(max_length=5, default="NULL")
    berkacamata = models.CharField(max_length=5, default="TIDAK")
    disabilitas = models.CharField(max_length=30)
    tinggi_badan = models.CharField(max_length=5, default="0")
    berat_badan = models.CharField(max_length=5, default="0")
    periode_masuk = models.CharField(max_length=20, default="NULL")
    asal_sekolah = models.CharField(max_length=200, default="NULL")
    npsn_asal_sekolah = models.CharField(max_length=40, default="NULL")
    no_ijazah = models.CharField(max_length=40, default="NULL")
    tanggal_lulus = models.DateField(default=date.today)
    no_registrasi_ppdb = models.CharField(max_length=20, default="NULL")
    no_hp = models.CharField(max_length=20, default="NULL")
    email= models.CharField(max_length=150, default="NULL")
    status_orang_tua = models.CharField(max_length=30, default="NULL")
    nama_ayah = models.CharField(max_length=150, default="NULL")
    nama_ibu = models.CharField(max_length=150, default="NULL")
    nama_wali = models.CharField(max_length=150, blank=True)
    alamat_orang_tua = models.TextField(blank=True)
    no_hp_orang_tua = models.CharField(max_length=20)
    last_update = models.DateTimeField(auto_now=False)
    class Meta:
        db_table = "tbl_siswa_data"