# Generated by Django 3.2.5 on 2021-07-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_siswa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataSiswa',
            new_name='SiswaData',
        ),
        migrations.AlterModelTable(
            name='siswadata',
            table='tbl_siswa_data',
        ),
    ]
