# Generated by Django 3.2.5 on 2021-07-23 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_siswa', '0002_auto_20210720_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siswadata',
            old_name='kd_desa',
            new_name='disabilitas',
        ),
        migrations.RenameField(
            model_name='siswadata',
            old_name='update_at',
            new_name='last_update',
        ),
        migrations.RenameField(
            model_name='siswadata',
            old_name='kd_kecamatan',
            new_name='no_hp_orang_tua',
        ),
        migrations.RemoveField(
            model_name='siswadata',
            name='kd_kabupaten',
        ),
        migrations.RemoveField(
            model_name='siswadata',
            name='kd_provinsi',
        ),
        migrations.RemoveField(
            model_name='siswadata',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='siswadata',
            name='penghasilan_ayah',
        ),
        migrations.RemoveField(
            model_name='siswadata',
            name='penghasilan_ibu',
        ),
        migrations.RemoveField(
            model_name='siswadata',
            name='penghasilan_wali',
        ),
        migrations.AddField(
            model_name='siswadata',
            name='agama',
            field=models.CharField(default='NULL', max_length=5),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='alamat_orang_tua',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='asal_sekolah',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='berat_badan',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='berkacamata',
            field=models.CharField(default='TIDAK', max_length=5),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='desa',
            field=models.CharField(default='NULL', max_length=15),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='desa_lahir',
            field=models.CharField(default='NULL', max_length=15),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='email',
            field=models.CharField(default='NULL', max_length=150),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='golongan_darah',
            field=models.CharField(default='NULL', max_length=5),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='kab',
            field=models.CharField(default='NULL', max_length=15),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='kab_lahir',
            field=models.CharField(default='NULL', max_length=15),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='kec',
            field=models.CharField(default='NULL', max_length=15),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='kec_lahir',
            field=models.CharField(default='NULL', max_length=15),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='nama_lengkap',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='no_hp',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='no_ijazah',
            field=models.CharField(default='NULL', max_length=40),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='no_registrasi_ppdb',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='npsn_asal_sekolah',
            field=models.CharField(default='NULL', max_length=40),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='periode_masuk',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='prov',
            field=models.CharField(default='NULL', max_length=15),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='prov_lahir',
            field=models.CharField(default='NULL', max_length=15),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='status_orang_tua',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='tanggal_lulus',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='siswadata',
            name='tinggi_badan',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='siswadata',
            name='jenis_kelamin',
            field=models.CharField(default='NULL', max_length=5),
        ),
        migrations.AlterField(
            model_name='siswadata',
            name='nama_ayah',
            field=models.CharField(default='NULL', max_length=150),
        ),
        migrations.AlterField(
            model_name='siswadata',
            name='nama_ibu',
            field=models.CharField(default='NULL', max_length=150),
        ),
        migrations.AlterField(
            model_name='siswadata',
            name='nama_wali',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='siswadata',
            name='nik',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AlterField(
            model_name='siswadata',
            name='nis',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AlterField(
            model_name='siswadata',
            name='nisn',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AlterField(
            model_name='siswadata',
            name='tanggal_lahir',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='siswadata',
            name='username',
            field=models.CharField(default='NULL', max_length=150),
        ),
    ]
