# Generated by Django 3.2.5 on 2021-07-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ppdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPeriodePpdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_periode', models.CharField(max_length=20)),
                ('nama_periode', models.CharField(max_length=100)),
                ('keterangan', models.TextField()),
                ('tahun_ajaran_awal', models.CharField(max_length=4)),
                ('tahun_ajaran_akhir', models.CharField(max_length=4)),
                ('mulai_tanggal', models.DateField()),
                ('akhir_tanggal', models.DateField()),
            ],
            options={
                'db_table': 'tbl_periode_ppdb',
            },
        ),
    ]
