# Generated by Django 3.2.5 on 2021-07-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('kata_sandi', models.CharField(max_length=200)),
                ('tipe_user', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
    ]
