# Generated by Django 3.2.5 on 2021-07-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AuthUser',
        ),
        migrations.AlterModelTable(
            name='authuser',
            table='tbl_auth_user',
        ),
    ]
