# Generated by Django 3.2.5 on 2021-07-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipe_user',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
