# Generated by Django 3.2.5 on 2021-07-23 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_auto_20210720_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthLogLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('waktu_login', models.DateTimeField()),
                ('ip_address', models.CharField(max_length=50)),
                ('user_agent', models.TextField()),
            ],
            options={
                'db_table': 'tbl_auth_log_login',
            },
        ),
        migrations.CreateModel(
            name='AuthRegistrasiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('kata_sandi', models.CharField(max_length=150)),
                ('tipe_user', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_auth_registrasi_siswa',
            },
        ),
        migrations.CreateModel(
            name='AuthSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_access', models.CharField(max_length=50)),
                ('secret_key', models.CharField(max_length=25)),
                ('npsn', models.CharField(max_length=20)),
                ('nama_sekolah', models.CharField(max_length=200)),
                ('email_sekolah', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_auth_sekolah',
            },
        ),
        migrations.AddField(
            model_name='authuser',
            name='aktif',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='authuser',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='tipe_user',
            field=models.CharField(max_length=30),
        ),
    ]
