# Generated by Django 3.2.5 on 2021-07-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0003_auto_20210723_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
