# Generated by Django 3.2.5 on 2021-07-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0007_auto_20210723_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authloglogin',
            name='waktu_login',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='authregistrasiuser',
            name='waktu_registrasi',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='login_last',
            field=models.DateTimeField(),
        ),
    ]
